const articles = [
{
id: "3",
title: "Derry Girls is my current favorite TV show",
m_title: "And I said to him, says I",
slug: "/archive/2024/derry-girls",
date: "2024/05/04",
p6: "",
p7: "I don’t much watch TV shows, but I have watched Derry Girls twice. It’s so good. My favorite characters are Clare and Colm.",
pb8: "I also got very curious about Northern Ireland while watching that show. This is bold paragraph. Keep writing like this.",
pi9: "I find Colm relaxing and quite interesting, I love the way he talks. This script provides 4 types of text: normal(p), italic(pi), bold (pb), and highlight(ph).",
pu10: "I also love sister Michael. I find it so funny that her full name was Geroge Michael. This is pu.",
img11: "/assets/3/derry-girls.webp",
imgalt12: "Lady Immaculate School",
imgby13: "Copyright Channel 4",
img14: "/assets/3/clare.webp",
imgalt15: "Clare from derry girls",
},
{
id: "2",
title: "That’s the best acting I have ever seen",
m_title: "Daniel Day Lewis is a god of acting",
slug: "/archive/2024/there-will-be-blood",
date: "2024/05/04",
tags: ["movie", "essay"],
someothermetadata: "this is some other meta data",
p8: "",
p9: "I watched There will be blood for its cinematography. I didn’t know Daniel Day Lewis then, but when I saw the movie, I couldn’t get him out of my mind. He is still inside.",
pb10: "How could someone act that perfectly? This is a bold paragraph. One draw back of this method is you can’t have bold part inside a normal or italic paragraph.",
img11: "/assets/2/blood-there.webp",
imgalt12: "Poster of the film",
imgby13: "Copyright Warner Bros or maybe whoever",
imgr14: "/assets/2/daniel.webp",
imgalt15: "Daniel Day Lewis",
imgby16: "Greatest actor ever",
p17: "I drink your milkshake. I drink it up. Remember for image fontsize 16, for alt 15 and for source or caption or whatever other information about the image font size 10. This is font size 11 and so the caption (font size 10) maye look the same size. So I would recommend to use font size 13 for texts instead of 11.",
},
{
id: "1",
title: "Forrest Gump is like a box of chocolate",
m_title: "Forrest Gump is like a box of chocolate",
slug: "/archive/2024/forrest-gump",
keywords: ["keyword1", "keyword2"],
info: "only keywords and tags are supported for array making",
date: "2024/05/04",
p8: "",
p9: "<a href=\"https://maybewikilink.com\" className=\"art-lnk\">Forrest Gump</a> was released the same year as Shawshank Redemption. Though released 30 years ago, before I was even born, it’s one of my favorite movies. Anyway this is the normal paragraph, which will have the suffix “p” before the counter.",
img10: "/assets/1/forrest.webp",
imgalt11: "Poster of the FG",
imgby12: "Copyright Warner Bros or maybe whoever",
pi13: "Life is like a box of chocolate, isn’t it?",
imgl14: "/assets/1/tom-hanks.webp",
imgalt15: "Tom  hanks",
imgby16: "Tom hanks’ picture",
pu17: "I cried when Forests met his son. This is font size 13 and as you can see and so probably it’s easier to see  that the caption above is font size 10 and it’s more distinguishable.",
},
{
id: "0",
title: "Why is The Shawshank Redemption still the best movie ever?",
m_title: "Why The Shawshank Redemption is still the best picture ever?",
m_desc: "The Shawshank Redemption was released in 1995. But it’s still relevant and talked about. Learn about this timeless movie.",
slug: "/archive/2024/shawshank-redemption-movie",
excerpt: "Brooks was here. So was Red.",
tags: ["movies", "essay", "movie review"],
keywords: ["greatest movie ever", "morgan freeman", "hope", "top imdb", "shawshank redemption"],
date: "2024/05/04",
p_date: "2024-05-04T09:00:00+05:45",
m_date: "2024-05-04T09:00:00+05:45",
photo: "/assets/0/shawshank-redemption.webp",
alt: "Poster of The Shawshank Redemption",
p14: "",
p15: "Though released 30 years ago, before I was even born, The Shawshank Redemption is my favorite movie. The ending was so beautiful. Read the <a href=\"https://en.wikipedia.org/wiki/The_Shawshank_Redemption\" className=\"art-lnk\">wiikipedia</a> This is not paragraph break, it’s because there is no space around $. Anyway this is the normal paragraph, which will have the suffix “p” before the counter.",
img16: "/assets/0/shawshank-redemption.webp",
imgalt17: "Poster of the Shawshank Redemption",
imgby18: "Copyright Warner Bros",
pb19: "I could hear Morgan Freeman talk all day. “Some birds are not meant to be caged,” he says in the movie. I think that’s true. This will have the suffix “pb” before the counter.",
imgr20: "/assets/0/brooks.webp",
imgalt21: "Brooks from Shawshank",
imgby22: "You can either give alt and caption or not. It’s not mandatory",
pi23: "The death of Brooks was very sad. I cried <a href=\"https://somewebsiteorlink.com\" className=\"art-lnk\">during that scene</a> . This will have the suffix “pi” before the counter. ",
pu24: "But we should always remember to be hopeful. This will have the suffix “ph” before the counter, and you can grab this and have your own distinct style.",
p25: "",
},

 ]; 
 export default articles;